enum ErrorTypes {
  DEFAULT = 'DEFAULT',

  //accommodation
  ACCOMMODATION_FAILED_TO_GET_SINGLE = 'ACCOMMODATION_FAILED_TO_GET_SINGLE',
  ACCOMMODATION_FAILED_TO_GET_LIST = 'ACCOMMODATION_FAILED_TO_GET_LIST',
}

export default ErrorTypes;
